-- 1) Lock down auto-suspend BEFORE doing anything expensive
ALTER WAREHOUSE COMPUTE_WH SET
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 2) Create the sandbox
CREATE DATABASE IF NOT EXISTS RAPPI_SANDBOX;
CREATE SCHEMA   IF NOT EXISTS RAPPI_SANDBOX.SYNTH;

-- 3) Tell Snowflake to use them by default in this worksheet
USE WAREHOUSE COMPUTE_WH;
USE DATABASE  RAPPI_SANDBOX;
USE SCHEMA    SYNTH;

-- 4) Confirm
SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_ROLE();
