SELECT COUNT(*) AS total_rows FROM ORDER_DIMENSIONS_SYNTH;

SELECT COUNTRY_CODE, COUNT(*) AS n
FROM ORDER_DIMENSIONS_SYNTH GROUP BY 1 ORDER BY 2 DESC;

SELECT ORDER_STATUS, COUNT(*) AS n,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS pct
FROM ORDER_DIMENSIONS_SYNTH GROUP BY 1;

SELECT DATE_TRUNC('month', ORDER_CREATED_AT) AS mo, COUNT(*) AS n
FROM ORDER_DIMENSIONS_SYNTH GROUP BY 1 ORDER BY 1;
